In [14]:
import numpy as np

#將下兩列array存成npz檔
array1 = np.array(range(30))
array2 = np.array([2,3,5])
with open('two_array.npz', 'wb') as f:
    np.savez(f, array1 = array1, array2 = array2)
npzfile = np.load('two_array.npz')
print(npzfile['array1'])
print(npzfile['array2'])

#讀取剛剛的npz檔，加入下列array一起存成新的npz檔
array3 = np.array([[4,5,6], [1,2,3]])
with open('multi_array.npz', 'wb') as g:
    np.savez(g, array1 = npzfile, array2 = array3)
new_npzfile = np.load('multi_array.npz')

print(new_npzfile['array1'])
print(new_npzfile['array2'])


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[2 3 5]
['array1' 'array2']
[[4 5 6]
 [1 2 3]]
